from tkinter import *
#import tkinter.messagebox as tmsg

def click(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get() + text)
        screen.update()

root = Tk()
root.geometry("744x900")
root.title("MY CALCULATOR")

scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvar = scvalue, font = "lucida 40 bold")
screen.pack(fill=X,padx=15,pady=5)

f = Frame(root, bg="gray")
b =  Button(f,text="9",font="lucida 36 bold",padx=15,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="8",font="lucida 36 bold",padx=15,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="7",font="lucida 36 bold",padx=15,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="C",font="lucida 36 bold",padx=15,pady=5,bg="red")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="gray")
b =  Button(f,text="6",font="lucida 36 bold",padx=18,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="5",font="lucida 36 bold",padx=18,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="4",font="lucida 36 bold",padx=18,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="/",font="lucida 36 bold",padx=18,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="gray")
b =  Button(f,text="3",font="lucida 36 bold",padx=17,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="2",font="lucida 36 bold",padx=17,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="1",font="lucida 36 bold",padx=17,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="*",font="lucida 36 bold",padx=17,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="gray")
b =  Button(f,text=".",font="lucida 36 bold",padx=16,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="0",font="lucida 36 bold",padx=16,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="%",font="lucida 36 bold",padx=16,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="+",font="lucida 36 bold",padx=16,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="gray")
b =  Button(f,text="(",font="lucida 36 bold",padx=20,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text=")",font="lucida 36 bold",padx=20,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="-",font="lucida 36 bold",padx=20,pady=5,bg="green")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
b =  Button(f,text="=",font="lucida 36 bold",padx=20,pady=5,bg="red")
b.pack(side = LEFT,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()

root.mainloop()